kind: pipeline
type: docker
name: default

steps:
  - name: docker
    image: plugin/docker
    settings:
      - username: nishantsr
      - password: pass
      - repo: foo/bar
      - debug: true

  - name: Run JS Unit Tests
    image: prairielearn/prairielearn
    commands:
      - npm install --silent
      - npm test

  # - name: Run Python UI Tests
  #   image: prairielearn/prairielearn
  #   commands: 
  #     - pip install -r requirements.txt --quiet
  #     - cd tests
  #     - python -m unittest discover ui -p "*_test.py"