kind: pipeline
type: docker
name: default

steps:
  - name: Run Autogenerator tests
    image: prairielearn/prairielearn
    commands: 
      - pip install -r requirements.txt --quiet
      - cd databaseCourse/elements/pl-sql-element
      # just run all test files
      - python -m unittest discover -p "*_test.py"
      # detailed run of one file
      # - python -m unittest -v autogenerator_test.py
      # - py -m unittest discover -p "*_test.py"

  - name: Run UI Tests
    image: prairielearn/prairielearn
    commands: 
      - pip install -r requirements.txt --quiet
      - yum update -y
      - yum install -y wget
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - yum localinstall -y google-chrome-stable_current_x86_64.rpm
      - rm google-chrome-stable_current_x86_64.rpm
      - cd tests/ui
      - python -m unittest discover -s . -p "*_test.py"
