kind: pipeline
type: docker
name: default

steps:
  - name: Run Tests
    image: prairielearn/prairielearn
    commands:
      - npm install
      - npm test
      - cd tests
      - py -m unittest discover ui -p "*_test.py"