kind: pipeline
type: docker
name: default

steps:
  - name: Run Autogenerator tests
    image: prairielearn/prairielearn
    commands: 
      - pip install -r requirements.txt --quiet
      - cd databaseCourse/elements/pl-sql-element
      # just run all test files
      - python -m unittest discover -p "*_test.py"
      # detailed run of one file
      # - python -m unittest -v autogenerator_test.py
      # - py -m unittest discover -p "*_test.py"


If you want to run your tests using an image that already has Selenium installed, and your Python tests are configured to run on localhost:3000, you can modify the drone.yml file accordingly. Here's an example:

yaml
Copy code
kind: pipeline
type: docker
name: default

steps:
  - name: Run Autogenerator tests
    image: prairielearn/prairielearn
    commands: 
      - pip install -r requirements.txt --quiet
      - cd databaseCourse/elements/pl-sql-element
      # just run all test files
      - python -m unittest discover -p "*_test.py"
      # detailed run of one file
      # - python -m unittest -v autogenerator_test.py
      # - py -m unittest discover -p "*_test.py"

  - name: Run UI Tests
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    commands: 
      - pip install -r requirements.txt --quiet
      - cd tests/ui
      - python -m unittest discover -s . -p "*_test.py"
