kind: pipeline
type: docker
name: default

steps:

  steps:
  - name: Verify Docker
    image: azipis/prairielearn-chrome:latest
    commands:
      - docker version


  # - name: Run Autogenerator tests
  #   image: prairielearn/prairielearn
  #   commands: 
  #     - pip install -r requirements.txt --quiet
  #     - cd databaseCourse/elements/pl-sql-element
  #     - python -m unittest discover -p "*_test.py"

  # - name: Run UI Tests
  #   image: azipis/prairielearn-chrome:latest
  #   commands: 
  #     - docker run -p 8080:8080 -d azipis/prairielearn-chrome
  #     - pip install -r requirements.txt
  #     - cd tests/ui
  #     - python -m unittest discover -s . -p "*_test.py"
  #     - docker stop $(docker ps -q --filter ancestor=azipis/prairielearn-chrome)

# services:
#   - name: selenium
#     image: selenium/standalone-chrome
#     ports:
#       -3000:3000

  # - name: Run Integration Tests
  #   image: selenium/standalone-chrome
  #   commands: 
  #     - pip install -r requirements.txt --quiet
  #     - cd tests/integration
  #     - python -m unittest discover -s . -p "*_test.py"
