kind: pipeline
type: docker
name: default

steps:
  - name: Run Tests
    image: prairielearn/prairielearn
    commands:
      - pip install -r requirements.txt
      - cd tests
      - py -m unittest sample_test.py