kind: pipeline
type: docker
name: default

steps:
  # - name: Run Autogenerator tests
  #   image: prairielearn/prairielearn
  #   commands: 
  #     - pip install -r requirements.txt --quiet
  #     - cd databaseCourse/elements/pl-sql-element
  #     - python -m unittest discover -p "*_test.py"

  - name: Install chromedriver_binary
    image: python:3.10
    commands:
      - pip install chromedriver-binary
      - cp -r /usr/local/bin/chromedriver /workspace/chromedriver  # Copy chromedriver to the workspace

  - name: Run UI Tests
    image: azipis/prairielearn-chrome:latest
    commands: 
      - pip install -r requirements.txt
      - cd tests/ui
      - python -m unittest discover -s . -p "*_test.py"

  # - name: Run Integration Tests
  #   image: selenium/standalone-chrome
  #   commands: 
  #     - pip install -r requirements.txt --quiet
  #     - cd tests/integration
  #     - python -m unittest discover -s . -p "*_test.py"
