kind: pipeline
type: docker

name: default

steps:
  - name: Run Tests
    image: python:3.9
    commands:
      - pip install -r requirements.txt
      - python -m unittest discover -s tests/unit -p "*_test.py"