kind: pipeline
type: docker
name: default

steps:
  # - name: Run JS Unit Tests
  #   image: prairielearn/prairielearn
  #   commands:
  #     - npm install --silent
  #     - npm test

  - name: Run Autogenerator tests
    image: prairielearn/prairielearn
    commands: 
      - pip install -r requirements.txt --quiet
      - cd databaseCourse/elements/pl-sql-element
  # just run all test files
      - python -m unittest discover -p "*_test.py"
  # detailed run of one file
  #     - python -m unittest -v autograder_test.py
  #     - py -m unittest discover -p "*_test.py"