version: '3.8'
services:
  pl:
    build:
      context: .
    image: prairielearn/prairielearn:latest
    ports:
      - 3000:3000
    volumes:
      - ./databaseCourse:/course
      - ./elements:/PrairieLearn/elements
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/pl_ag_jobs:/jobs

    container_name: pl
    environment:
      - HOST_JOBS_DIR=${HOME}/pl_ag_jobs
      - NODEMON=true
  drone:
    image: drone/drone
    container_name: drone
    restart: always
    ports: 
      - 8090:80
      - 443:443
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./drone:/data
    environment:
    - DRONE_GITHUB_CLIENT_ID=${DRONE_GITHUB_CLIENT_ID}
    - DRONE_GITHUB_CLIENT_SECRET=${DRONE_GITHUB_CLIENT_SECRET}
    - DRONE_RUNNER_CAPACITY=2
    - DRONE_SERVER_HOST=cc2d-64-251-70-60.ngrok-free.app
    - DRONE_SERVER_PROTO=https
    - DRONE_TLS_AUTOCERT=true
    - DRONE_USER_CREATE=username:nishant-sr,admin:true
    - DRONE_COOKIE_SECRET=correct-horse-battery-staple
